nats:
  host: "localhost"
  port: "4223"
  cluster_id: "test-cluster"
  client_id: "test-client"
  publisher_id: "test-publisher"
  channel: "test-channel"

db:
  Host: "localhost"
  Port: "5432"
  Uname: "postgres"
  NameDB: "postgres"
  SSL: "disable"
  PASS: "qwerty"
  DriverName: "postgres"

httpsrv:
  host: "localhost"
  port: 8080